### ISSUE TITLE
关于LOL训练

### ISSUE THREAD

**Issue by MoWangDaRen** [AlexZou14/Wave-Mamba#10]
在LOL的yml中，网络结构设置的是UWMamba，但是我没有找到命名是UWMamba的类，是缺失文件了吗，还是yml没有更新

**Comment by AlexZou14** [comment]
我改名字忘改回来了> 在LOL的yml中，网络结构设置的是UWMamba，但是我没有找到命名是UWMamba的类，是缺失文件了吗，还是yml没有更新

**Comment by MoWangDaRen** [comment]
好的，感谢您的贡献


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月12日(周二) 下午4:26
收件人: ***@***.***&gt;;
抄送: &quot;Jingtao ***@***.******@***.***&gt;;
主题: Re: [AlexZou14/Wave-Mamba] 关于LOL训练 (Issue #10)




 
我改名字忘改回来了&gt; 在LOL的yml中，网络结构设置的是UWMamba，但是我没有找到命名是UWMamba的类，是缺失文件了吗，还是yml没有更新
 
&mdash;
