### ISSUE TITLE
指标复现差距较大

### ISSUE THREAD

**Issue by Zxuans** [AlexZou14/Wave-Mamba#11]
为什么我在没有修改任何参数的情况下，LOL上训练的best PSNR不到23？

**Comment by Zxuans** [comment]
看到有计算psnr_gray，就懂咋回事喽

**Comment by Zxuans** [comment]
我有一个问题啊，自己用单通道算PSNR SSIM 别人的方法呢？别人的方法单通道有那么差吗？拿自己的单通道结果和别人的三通道对比，真够招笑的

**Comment by XUREN7** [comment]
> 为什么我在没有修改任何参数的情况下，LOL上训练的best PSNR不到23？

他这个给的模型我测了确实是26，我还没训练（环境配的问题太多），你的还有记录吗，懒得跑了

**Comment by wanghu178** [comment]
我跑了LOLV2_real的数据集，目前复现出来最好的psnr是20.761632， 但是作者给的模型可以干到29。 不知道是环境差异还是怎么了。
![image](https://github.com/user-attachments/assets/b47a04e1-49c2-4809-8846-789557f54d2b)

**Comment by XUREN7** [comment]
有实验记录可太棒了，非常感谢

**Comment by Zxuans** [comment]
> 我跑了LOLV2_real的数据集，目前复现出来最好的psnr是20.761632， 但是作者给的模型可以干到29。 不知道是环境差异还是怎么了。 ![image](https://private-user-images.githubusercontent.com/34547726/392769319-b47a04e1-49c2-4809-8846-789557f54d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDI4MzgsIm5iZiI6MTczMzQwMjUzOCwicGF0aCI6Ii8zNDU0NzcyNi8zOTI3NjkzMTktYjQ3YTA0ZTEtNDljMi00ODA5LTg4NDYtNzg5NTU3ZjU0ZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNThhYTFiMWU3MWM3MWY2NDNmZDU1M2NmZDgxNmFmZTYyNWM5ZmNjNGJlYjA2Yjc4Mzc2MzMxZDQwMDg1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._QZvD3UaMOH3WunqMIEgX6uKwLYFA5S2Ph81Cym4-3k)

别怀疑自己了兄弟，懂得都懂，LOLv1上不了23，LOLv2上不了22，他的结果肯定是用手法了，初步怀疑是直接在测试集上训了，环境能差一两个点顶天了，这差太多了

**Comment by Zxuans** [comment]
> > 为什么我在没有修改任何参数的情况下，LOL上训练的best PSNR不到23？
> 
> 他这个给的模型我测了确实是26，我还没训练（环境配的问题太多），你的还有记录吗，懒得跑了

![1733402747541](https://github.com/user-attachments/assets/c4573383-fce6-4cf1-b5cf-529f99ae139a)
xunl训了好几次，直接润就行了，这篇纯编的结果

**Comment by AlexZou14** [comment]
> 我跑了LOLV2_real的数据集，目前复现出来最好的psnr是20.761632， 但是作者给的模型可以干到29。 不知道是环境差异还是怎么了。 ![image](https://private-user-images.githubusercontent.com/34547726/392769319-b47a04e1-49c2-4809-8846-789557f54d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjkzNjUsIm5iZiI6MTczMzk2OTA2NSwicGF0aCI6Ii8zNDU0NzcyNi8zOTI3NjkzMTktYjQ3YTA0ZTEtNDljMi00ODA5LTg4NDYtNzg5NTU3ZjU0ZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAyMDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGEyMmFjNTU3NjkxMjU1ZTZhNDJjMDA2ODI4OGJmOTc4NGI5OTVlNmQ0NWVkOGUwOWRkOGQ5YzNkNDAzYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q06oYxJ3_sGqjdAyQfvIkSXqUHkIrt_32-sI5JCkZz8)

你好，我这边是根据DiffLL的测试方式，是采用LOLv1的训练好的权重进行测试的LOLv2Real，由于LOLv1训练集中有部分数据和LOLv2Real测试集有部分重复，所以会相对来说比较高。没有在LOLv2Real的训练数据上进行训练

**Comment by wanghu178** [comment]
哦哦 我说呢。 谢谢回复。

**Comment by AlexZou14** [comment]
> > > 为什么我在没有修改任何参数的情况下，LOL上训练的best PSNR不到23？
> > 
> > 
> > 他这个给的模型我测了确实是26，我还没训练（环境配的问题太多），你的还有记录吗，懒得跑了
> 
> ![1733402747541](https://private-user-images.githubusercontent.com/186905038/392820817-c4573383-fce6-4cf1-b5cf-529f99ae139a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjkzNjUsIm5iZiI6MTczMzk2OTA2NSwicGF0aCI6Ii8xODY5MDUwMzgvMzkyODIwODE3LWM0NTczMzgzLWZjZTYtNGNmMS1iNWNmLTUyOWY5OWFlMTM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwMjA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjVkY2JkNDlmZmFhYWQxOGRhNDE4MDM0MzFmMDljNDI2YzY3YmM0NGUzYWQ4MDJlNWM4NmRlNjJmY2RkZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TvNDDA9dF9KYtKWZnx1SRbs2hofPkyHpUYmL6TBrNLQ) xunl训了好几次，直接润就行了，这篇纯编的结果

你好，我看了一下我的log，我第一次训练的log里面就有25+的PSNR，后面我又多次在第一次训练的最好的权重下进行finetune多次才到26+的PSNR
初步训练log如下：
![image](https://github.com/user-attachments/assets/f9070fa6-6e40-45e5-a9bf-ae32a1395779)
fintune训练的 log：
![image](https://github.com/user-attachments/assets/9701af3e-29e4-4ac0-9734-523bd2dec9b7)

**Comment by Whisker42** [comment]
> > > > 为什么我在没有修改任何参数的情况下，LOL上训练的best PSNR不到23？
> > > 
> > > 
> > > 他这个给的模型我测了确实是26，我还没训练（环境配的问题太多），你的还有记录吗，懒得跑了
> > 
> > 
> > ![1733402747541](https://private-user-images.githubusercontent.com/186905038/392820817-c4573383-fce6-4cf1-b5cf-529f99ae139a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjkzNjUsIm5iZiI6MTczMzk2OTA2NSwicGF0aCI6Ii8xODY5MDUwMzgvMzkyODIwODE3LWM0NTczMzgzLWZjZTYtNGNmMS1iNWNmLTUyOWY5OWFlMTM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwMjA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjVkY2JkNDlmZmFhYWQxOGRhNDE4MDM0MzFmMDljNDI2YzY3YmM0NGUzYWQ4MDJlNWM4NmRlNjJmY2RkZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TvNDDA9dF9KYtKWZnx1SRbs2hofPkyHpUYmL6TBrNLQ) xunl训了好几次，直接润就行了，这篇纯编的结果
> 
> 你好，我看了一下我的log，我第一次训练的log里面就有25+的PSNR，后面我又多次在第一次训练的最好的权重下进行finetune多次才到26+的PSNR 初步训练log如下： ![image](https://private-user-images.githubusercontent.com/62631470/394980810-f9070fa6-6e40-45e5-a9bf-ae32a1395779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzE4MTQsIm5iZiI6MTczNDc3MTUxNCwicGF0aCI6Ii82MjYzMTQ3MC8zOTQ5ODA4MTAtZjkwNzBmYTYtNmU0MC00NWU1LWE5YmYtYWUzMmExMzk1Nzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA4NTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGRiN2ZhN2ViYmI1Zjg0NGFlY2EwM2U2MDQyMGJjOWVmNDFhMDkzZjY3ZThkOTU3NDIxNDE0YjlhMTc1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2e0YTFt4HR_74Bwtq8zA-e6I__Ak8xUr-uhYzZ_BLMY) fintune训练的 log： ![image](https://private-user-images.githubusercontent.com/62631470/394981404-9701af3e-29e4-4ac0-9734-523bd2dec9b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzE4MTQsIm5iZiI6MTczNDc3MTUxNCwicGF0aCI6Ii82MjYzMTQ3MC8zOTQ5ODE0MDQtOTcwMWFmM2UtMjllNC00YWMwLTk3MzQtNTIzYmQyZGVjOWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA4NTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2I3NDhkZjk5MTkwYjFhNTE2MDg5MWFiNTc1NWNmMTk3MTQ5MWEzODgwY2RhNzQ2ZDMxODkzYzFkMGIwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R7NNFnVQ_0MbQ4mQHqUbmoaiASJM8BMOK51Saqr94NA)

你好，请问微调的学习率和训练epoch是怎么设置的？

**Comment by MoWangDaRen** [comment]
> > 我跑了LOLV2_real的数据集，目前复现出来最好的psnr是20.761632， 但是作者给的模型可以干到29。 不知道是环境差异还是怎么了。 ![image](https://private-user-images.githubusercontent.com/34547726/392769319-b47a04e1-49c2-4809-8846-789557f54d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDI4MzgsIm5iZiI6MTczMzQwMjUzOCwicGF0aCI6Ii8zNDU0NzcyNi8zOTI3NjkzMTktYjQ3YTA0ZTEtNDljMi00ODA5LTg4NDYtNzg5NTU3ZjU0ZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNThhYTFiMWU3MWM3MWY2NDNmZDU1M2NmZDgxNmFmZTYyNWM5ZmNjNGJlYjA2Yjc4Mzc2MzMxZDQwMDg1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._QZvD3UaMOH3WunqMIEgX6uKwLYFA5S2Ph81Cym4-3k)
> 
> 别怀疑自己了兄弟，懂得都懂，LOLv1上不了23，LOLv2上不了22，他的结果肯定是用手法了，初步怀疑是直接在测试集上训了，环境能差一两个点顶天了，这差太多了

这太令人难过了 我关注了他这篇文章好久,感觉他效果特别好,没想到大家复现都是这样的,看到作者回复说测试集跟训练模型时用的数据还有重复的,要晕了...那个diffll我也看过还多次

**Comment by AlexZou14** [comment]
> > > 我跑了LOLV2_real的数据集，目前复现出来最好的psnr是20.761632， 但是作者给的模型可以干到29。 不知道是环境差异还是怎么了。 ![image](https://private-user-images.githubusercontent.com/34547726/392769319-b47a04e1-49c2-4809-8846-789557f54d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDI4MzgsIm5iZiI6MTczMzQwMjUzOCwicGF0aCI6Ii8zNDU0NzcyNi8zOTI3NjkzMTktYjQ3YTA0ZTEtNDljMi00ODA5LTg4NDYtNzg5NTU3ZjU0ZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNThhYTFiMWU3MWM3MWY2NDNmZDU1M2NmZDgxNmFmZTYyNWM5ZmNjNGJlYjA2Yjc4Mzc2MzMxZDQwMDg1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._QZvD3UaMOH3WunqMIEgX6uKwLYFA5S2Ph81Cym4-3k)
> > 
> > 
> > 别怀疑自己了兄弟，懂得都懂，LOLv1上不了23，LOLv2上不了22，他的结果肯定是用手法了，初步怀疑是直接在测试集上训了，环境能差一两个点顶天了，这差太多了
> 
> 这太令人难过了 我关注了他这篇文章好久,感觉他效果特别好,没想到大家复现都是这样的,看到作者回复说测试集跟训练模型时用的数据还有重复的,要晕了...那个diffll我也看过还多次

你好，我只有LOLv2是采用了LOLv1的训练权重测试的，其他测试集都是在对应的训练集训练后，再在测试集进行测试的。而且很多早期方法也是在LOLv1上训练的权重对LOLv2进行测试。

**Comment by AlexZou14** [comment]
> > > > > 为什么我在没有修改任何参数的情况下，LOL上训练的best PSNR不到23？
> > > > 
> > > > 
> > > > 他这个给的模型我测了确实是26，我还没训练（环境配的问题太多），你的还有记录吗，懒得跑了
> > > 
> > > 
> > > ![1733402747541](https://private-user-images.githubusercontent.com/186905038/392820817-c4573383-fce6-4cf1-b5cf-529f99ae139a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjkzNjUsIm5iZiI6MTczMzk2OTA2NSwicGF0aCI6Ii8xODY5MDUwMzgvMzkyODIwODE3LWM0NTczMzgzLWZjZTYtNGNmMS1iNWNmLTUyOWY5OWFlMTM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwMjA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjVkY2JkNDlmZmFhYWQxOGRhNDE4MDM0MzFmMDljNDI2YzY3YmM0NGUzYWQ4MDJlNWM4NmRlNjJmY2RkZTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TvNDDA9dF9KYtKWZnx1SRbs2hofPkyHpUYmL6TBrNLQ) xunl训了好几次，直接润就行了，这篇纯编的结果
> > 
> > 
> > 你好，我看了一下我的log，我第一次训练的log里面就有25+的PSNR，后面我又多次在第一次训练的最好的权重下进行finetune多次才到26+的PSNR 初步训练log如下： ![image](https://private-user-images.githubusercontent.com/62631470/394980810-f9070fa6-6e40-45e5-a9bf-ae32a1395779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzE4MTQsIm5iZiI6MTczNDc3MTUxNCwicGF0aCI6Ii82MjYzMTQ3MC8zOTQ5ODA4MTAtZjkwNzBmYTYtNmU0MC00NWU1LWE5YmYtYWUzMmExMzk1Nzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA4NTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGRiN2ZhN2ViYmI1Zjg0NGFlY2EwM2U2MDQyMGJjOWVmNDFhMDkzZjY3ZThkOTU3NDIxNDE0YjlhMTc1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2e0YTFt4HR_74Bwtq8zA-e6I__Ak8xUr-uhYzZ_BLMY) fintune训练的 log： ![image](https://private-user-images.githubusercontent.com/62631470/394981404-9701af3e-29e4-4ac0-9734-523bd2dec9b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzE4MTQsIm5iZiI6MTczNDc3MTUxNCwicGF0aCI6Ii82MjYzMTQ3MC8zOTQ5ODE0MDQtOTcwMWFmM2UtMjllNC00YWMwLTk3MzQtNTIzYmQyZGVjOWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA4NTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2I3NDhkZjk5MTkwYjFhNTE2MDg5MWFiNTc1NWNmMTk3MTQ5MWEzODgwY2RhNzQ2ZDMxODkzYzFkMGIwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R7NNFnVQ_0MbQ4mQHqUbmoaiASJM8BMOK51Saqr94NA)
> 
> 你好，请问微调的学习率和训练epoch是怎么设置的？

我一般都是减半学习率，epoch数目不变来进行微调的

**Comment by MoWangDaRen** [comment]
好的，我一直在用LOLv2real上训练测试的，我会用v1试试，感谢您的工作


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月23日(周一) 下午3:58
收件人: ***@***.***&gt;;
抄送: &quot;Jingtao ***@***.******@***.***&gt;;
主题: Re: [AlexZou14/Wave-Mamba] 指标复现差距较大 (Issue #11)




    
我跑了LOLV2_real的数据集，目前复现出来最好的psnr是20.761632， 但是作者给的模型可以干到29。 不知道是环境差异还是怎么了。 
  
别怀疑自己了兄弟，懂得都懂，LOLv1上不了23，LOLv2上不了22，他的结果肯定是用手法了，初步怀疑是直接在测试集上训了，环境能差一两个点顶天了，这差太多了
  
这太令人难过了 我关注了他这篇文章好久,感觉他效果特别好,没想到大家复现都是这样的,看到作者回复说测试集跟训练模型时用的数据还有重复的,要晕了...那个diffll我也看过还多次
  
你好，我只有LOLv2是采用了LOLv1的训练权重测试的，其他测试集都是在对应的训练集训练后，再在测试集进行测试的。而且很多早期方法也是在LOLv1上训练的权重对LOLv2进行测试。
 
&mdash;

**Comment by chaoyue12345678** [comment]
您好兄弟 问一下 您的是在 Ubuntu >= 22.04上进行训练的 我可以在其他系统上面跑吗 在配置环境的时候出现了问题

**Comment by jujujujuz** [comment]
> 我有一个问题啊，自己用单通道算PSNR SSIM 别人的方法呢？别人的方法单通道有那么差吗？拿自己的单通道结果和别人的三通道对比，真够招笑的

![Image](https://github.com/user-attachments/assets/be036c59-09f6-4ba7-a5b2-2832dd4f6b00)

![Image](https://github.com/user-attachments/assets/72c9564f-77f1-4b29-b0d8-3eec852ab1d9)

这是我们复现lolv1的结果，yaml使用是作者公开的lolyaml并没有任何改动，cuda使用的是12.1
