### ISSUE TITLE
多卡训练

### ISSUE THREAD

**Issue by LiuXD1011** [AlexZou14/Wave-Mamba#7]
你好，想follow你的工作做一些下游的任务。我用双卡训练的时候出现了这个情况，可以给点建议不？
![image](https://github.com/user-attachments/assets/332d584c-c0c5-42fa-a8bf-89f3002ccdec)

**Comment by LiuXD1011** [comment]
我训练的时候发现，为啥增大batchsize，训练会变慢很多，这是咋回事啊？泪目。

**Comment by AlexZou14** [comment]
你好，我这个目前不太支持多卡训练

**Comment by LiuXD1011** [comment]
好的，谢谢
