### ISSUE TITLE
关于指标

### ISSUE THREAD

**Issue by caojiale555** [AlexZou14/Wave-Mamba#8]
你好，请问评价psnr ssim 指标时进行gt 校正吗，计算psnr 的代码在哪里？

**Comment by caojiale555** [comment]
from comput_psnr_ssim import calculate_ssim as ssim_gray
from comput_psnr_ssim import calculate_psnr as psnr_gray
请问comput_psnr_ssim这个文件怎么下载

**Comment by AlexZou14** [comment]
你好 我没有做gt校正，采用pyiqa这个库的指标计算方式测的

**Comment by ooojiang** [comment]
from comput_psnr_ssim import calculate_ssim as ssim_gray
from comput_psnr_ssim import calculate_psnr as  #psnr_gray
同问comput_psnr_ssim这个文件怎么下载

**Comment by Zxuans** [comment]
> 你好 我没有做gt校正，采用pyiqa这个库的指标计算方式测的

推理当然不用gt校正啦，训练已经做了test集校正了，gt校正太low了
